### ISSUE TITLE
슬라이드 쇼 진입 시 페이지 번호 출력 옵션 필요해요!

### ISSUE THREAD

**Issue by totuworld-woowa** [woowacourse-teams/2020-zeze#229]
### Non-technical Feature

- [x] 페이지 제일 상단에 showPageNumber 필드를 수신해서 true 일 때 좌측이나 우측 하단에 페이지 번호를 표시한다.
- [ ] (추가로) 슬라이드쇼 모드 진입 시에 처음부터 보기 버튼이랑 이어보기 버튼을 분리하면 좋을 듯해요. 지속적으로 작업하다보면 이 둘을 병행해서 쓰게되더라고요.

잘 보고 갑니다 👍  힘내세요!!!!

**Comment by woonjangahn** [comment]
resolved in #248
